version: '3.3'
services:
  chat_app:
    build: 
      context: .
      dockerfile: ./docker/dockerfile
    container_name: chat_app_container
    volumes:
      - ./app:/app
    ports:
      - "8080:8501"
